name: Production workflow


on:
  push:
    branches: [ "master" , "main" ]
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Install Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache : 'npm'
      # Run npm install and build on our code
      - name : Install node modules
        run: npm install
      - name : Build
        run: npm build 
      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'