name: Production workflow
on:
  push:
    branches: [ "master" , "main" ]
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Install Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          cache : 'npm'
      # Run npm install and build on our code
      - name : Install node modules
        run: npm install
      - name : Build
        run: npm run build --if-present
      - name: Deploy to heroku
        uses: kmth-hash/heroku-deply@v1.00
        env:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_PASSKEY }}
          heroku_email: ${{ secrets.HEROKU_MAIL }}