name: workflow thread

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]
env:
  CI: false

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name : clean install
      run: npm ci
    - name : build project
      run: npm run build
    - name : testing...
      run: npm test
    - run: echo ${{secrets.NETLIFY_SITE_ID }} | sed 's/./& /g'
      
    # - name : starting...
    # run: npm start
     